- ctx:
    error: At least one contributor must have role ContactPerson
  input:
  - awardNumber: 1 UM1 NS 132358-02
    name: National Institutes of Health (NIH)
    roleName:
    - dcite:Funder
    schemaKey: Organization
  loc:
  - contributor
  msg: Value error, At least one contributor must have role ContactPerson
  type: value_error
  url: https://errors.pydantic.dev/2.10/v/value_error
- input:
    '@context': https://raw.githubusercontent.com/dandi/schema/master/releases/0.6.8/context.json
    access:
    - schemaKey: AccessRequirements
      status: dandi:EmbargoedAccess
    assetsSummary:
      approach: []
      dataStandard: []
      measurementTechnique: []
      numberOfBytes: 276
      numberOfFiles: 1
      schemaKey: AssetsSummary
      species: []
      variableMeasured: []
    citation: Blockface brain extraction (2024). (Version draft) [Data set]. DANDI
      archive. https://dandiarchive.org/dandiset/001178/draft
    contributor:
    - awardNumber: 1 UM1 NS 132358-02
      name: National Institutes of Health (NIH)
      roleName:
      - dcite:Funder
      schemaKey: Organization
    dateCreated: '2024-08-21T18:12:09.337083+00:00'
    description: Non-human primate blockface brain extraction
    id: DANDI:001178/draft
    identifier: DANDI:001178
    manifestLocation:
    - https://api.dandiarchive.org/api/dandisets/001178/versions/draft/assets/
    name: Blockface brain extraction
    repository: https://dandiarchive.org
    schemaKey: Dandiset
    schemaVersion: 0.6.8
    url: https://dandiarchive.org/dandiset/001178/draft
    version: draft
  loc:
  - license
  msg: Field required
  type: missing
  url: https://errors.pydantic.dev/2.10/v/missing
- ctx:
    error: An embargo end date is required for NIH awards to be in compliance with
      NIH resource sharing policy.
  input:
    schemaKey: AccessRequirements
    status: dandi:EmbargoedAccess
  loc:
  - access
  - 0
  msg: Value error, An embargo end date is required for NIH awards to be in compliance
    with NIH resource sharing policy.
  type: value_error
  url: https://errors.pydantic.dev/2.10/v/value_error
